[build]
     publish = "build"
     command = "npm run build"

[[redirects]]     
from = "/*"
  to = "/.netlify/identity/login"
  status = 302
  force = true
  conditions = {Role = ["*"]}
  
[[plugins]]
     package = "netlify-plugin-password-protection"
[[headers]]
  # Optional: Set a custom error page for unauthorized access
  for = "/.netlify/identity/error"
[headers.values]
    X-Frame-Options = "DENY"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self'; frame-src 'self';"

[context]
  # different settings for specific branches or deploys
  dev = {password = 0gdocs2024}
  # Add more contexts as needed
   